language: go
go:
- 1.7
addons:
  apt:
    packages:
    - upx-ucl
script:
- make release
- upx bin/etcdcd
deploy:
  provider: releases
  api_key:
    secure: Eu9bNS97IeZ1mp0asYybJhsZ6mOjlf6TLPuvtbd+qOSzmn3zzWBiR2m9DVRf/ysVnL6uC5iXifsvL7jpouEfqK0W0X3qyeV+pOOJ9+m5n9CyR6JGUikK4LozXvJrnvArdwCFAeqMp1O67g4uHabYcOyxW4QTO7895iI+FVnbQUS581MlGr3Iu6BV6cr3yczUOk/ZmLzCJ7mcqcPulVDBTgdhZZT5xaUR+Is1aTHZM+SerJEh1CEHH+dAhpQxfxw/5+kSDDsog1nIbP5r+/1ua/AmIPowSz/3Z5dJQqJXyalcgdIdrNN4kwJAIOUJDL0Oo3qLsdEUMHflJLlrYg8L9zEROQteoR3nWyIBLZEMVWRbormI0CVpWebGP5Qq4d2FLnoF6OEQXlRqyMwEvJiodhm34SOW5o92+XFllpY9yAJQdxu66RTRig+mp4S2zsytYx9vhzsY9HcS/qg8RRQVhjNdkjdW6bwtBxOFKxVBW/dVr8pDO6ldq6VcAsrz6pKeGk3Rm/IN3oq0FyJMFnCm8o27vs2cMOuTMLNaiBRKyERXoOBZ3ochbQrnIc+1rqINu4r6O42YPaxKQeMq99roT0tYJ03THaiBOlXvJaMg4RI6BX2Hc4hNAn7++/a/Jazb829xG3K1nzeN0qGE3seY7CsVq3+IvvWJvD0qiDQC9ng=
  file: bin/etcdcd
  on:
    repo: matt-deboer/etcdcd
    tags: true
after_deploy:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=mattdeboer/etcdcd
- docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .
- docker push $REPO:$TRAVIS_TAG
- docker tag $REPO:$TRAVIS_TAG $REPO:latest
- docker push $REPO:latest
env:
  global:
  - secure: aWoSsQA7AUYWTKPcOo07nRB6eXRbQ0DrvpyZYdoFeWJ84GU3BWmYZRcCwmeNOGWVYxaQlGjxOlDAC/Cvv0qoVgJdbL9aTlJZY3s7utYSYfxXKExviqmdqb9ZBBVa5HlH986We1KAf19kq0umkdabho5CWsiEUpD3+UsPoZgwTqSjLqFS5AjPsF11SzvUSVfofw1fH9zfUXLh8omLVFSgQ4u7zWs0tV0iOSugwny01Vy8q6IAFjKe8ZVbeliOE36L6plUHGhCcvyERMO9+leoteFRTDRqWNTUBW8tanY2nhdfZ8aolvA8I6yYALPO8wbVJp1s9LV/ewtYNrea2p4buvum5ts7YFRBNizwcNxfj65YOTJZxxEtaa7Sh9SOiJ5k0mDJWZWzOkQ5UsTCuoPGrrttljl777hHZBAt199eLd9Eetvz27Yt15HpGM6drRgCYDmtM1opKWG+3+22ml3KCMwmdYUjzu8hDP0nwHF5m1pKLw/aBiai0gxd7AcuUeDpMBJO55AosHggm30EJ7qLGWhcbJGLhkqy4OyCGUwRw6cuSW3GPhdHfehuj3yquKES3kWFHquBwJ2PdhT5I5JDAijVJvSq1SeIbwCuRV0aZfRg28EMHe3a1KGDW7D/D74kuVFDFJsu1UAELVm+4MlR1/CkrQtwgjKB1KgLHp0abk8=
  - secure: dPAo6nr3GAwMN8sWxbV0HwMpLjq9muB91Y3K7N3DchhxkHH9nEN3iNpsWlfDLbKbBBLg1Q4z94rJVl3WNz2i/4NTr93L04tkuUyPwQs8GKT4a1Tep/ECzXgtfZtdOz0cN+k5qD1ZfvfdCOgsgDansU96g0e0wS9XxvapWDKKQW+C5osor9ZpIvho8L0cICUpKAuTNAg88UfgakW2hFgBHRFsh/8uH5hqDe/qTHa204UJA8zD7hBDkU/S9fWn8PlPtY1YdyCHucE/pQa3sEdbcB19zTjGTmZAsha/c4eFFAajeOmTkyCe8j+SMRydhfT+Qc6i7sPReqPQ/NRuoaPiKSXkG5DV10L3E/f2Ihm4E5Fm032UMmonEqZc8jhZCdwGDKh63BLQTr40UoXHsLOvLQGBknbizMAviecOpf2Pmn2mHDAHAby43t7fX0rdJg4F1hhV4ilxX8py7GxK9/FjuEaTeVRZ7+T0HgeRYq0J9w75zEWfcueJYBRj8MPc83GBcN5wJBkXd9IeTj7C1QsQo34Vkj0rzbYd/i478qsPv/4Oaehww8j8ucNz0DKi1bgsUJ/tfDlVkT4DjkZAZ4j7MPMI/hUQsCLAkwP+3+dgz8uazBdDEnzGIQqshd8o8DL/SfE0bAgWAssgl1QcLiKiNlU8XJPyDQSlzQ2CEvueadA=
  - secure: OPwByk+pjjqP3pYiM6IizEdZ6EjwcznvQH8UXYIYsS7tkYOdP/cO7Mp4Mj7QiEGQnhcdrJIYA0+7Wj4RnUN+Oo0dzUtWNtngg1pwz9Ft91G2+TUZEss8Z3WDABdjH89/p35yRwN3eKzyfQqSPySqsn8yj5ljX0g4dvG47tVKVtQ5UaHYadK2jwS1Y9FyXSljWJyTHZnKgne5ZK77xme1FZWwtlF5mA09IWkAeB+ddXakJWiE4l/zhwxYmlpjHaqxjFHyzf75QxJGyw5O6NzDz++HlWObXLHKq08mVS39HZ7QwuZ4VultPZ7Tp2Bha7ej5ePyrDfUl9F1QqZCnw/7eiFpCmkQI44F4O6KL2QZSNnUKZQjrMuLxRnKAlEyDJA+R+6ZVVH7DBtNbSm0ZljA9Ob5P2i3S8BoAv9YDmJV4xQOMALhMLZteINocrhffZ7uadKesp2aRSuYY8aTesWgyTQgZLSn7yiQDDkJnj2F23lUqJ0mtok86P0f6upt+aGTtxC/oa8T0kMO7OqCqNVWNiZFhrnTF8iRRgplvANiGz87LQz6hgcHGYb2aJgadVByVxaaHnHG55GbghGeaLl4G6h/lrtVz+73IGtOjwxlcvDfXDcsqI/s/S/y1fdDYlqZ0Ebp0dRpCkvbcZ3LuAC4Y3cPN4Z+Uhcd2JgRSxaB/kc=
